
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.7
      with:
        
        script: |
          cd my-app
          rm -rf build
          npm install 
          npm run build
          
          cp -rf ../client/build build
          rm -rf admin
          cp -rf ../admin/build admin
          pm2 restart server.js
